# Generated by Django 5.2.4 on 2025-08-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxipark', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arrived', 'Arrived'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
